In [ ]:
#importar numpy

In [1]:
import numpy as np

In [2]:
a = np.arange(5,20,2)
print(a)

[ 5  7  9 11 13 15 17 19]


In [3]:
d=np.zeros((3,4))
print(d)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
